= Mon premier projet Maven

Maven est devenu populaire grâce au principe de "convention over configuration". Ce qui veut dire qu'un projet Maven ressemble à tout autre projet Maven.
En effet, dans un projet Maven, il y aura toujours 3 éléments :

- un fichier POM
- des conventions sur les noms et l'agencement des répertoires
- des repositories

L'autre aspect est l'existence d'un écosystème varié de plugin permettant de faire tout est n'importe quoi.

== Le fichier POM

Le fichier "pom.xml" est le fichier central de description du projet. Il permet de définir toutes les informations du projet dont les suivantes :

- le groupId
- l'artifactId
- la  version du projet
- la description du projet
- l'équipe
- les dépendances
- les plugins
- la manière de construire le projet
- le serveur d'intégration continue
- les repositories à utiliser
- la documentation à générer
- ...

En bref, il s'agit de votre nouveau meilleur ami (ou pas...)
Pour plus d'informations sur le POM allez voir https://maven.apache.org/pom.html#What_is_the_POM[ici]

Voici l'exemple du pom le plus minimaliste :

[source,xml]
----
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mycompany.app</groupId>
  <artifactId>my-app</artifactId>
  <version>1.0.0</version>
</project>
----

== Les conventions

Le groupId est l'identifiant unique du projet parmis tous les projets existants.

L'artifactId est le nom du jar sans la version.

La structure d'un répertoire Maven suit l'arborescence suivante :

[ditaa]
----
    +-----+
    | src |
	+---+-+
		|   +------+
		+-->| main |
		|	+---+--+
		|		|   +------+                                  /---------------\
		|		+-->| java |--------------------------------->|Sources Java   |
		|		|	  +------+                                  \---------------/
		|		|   +------------+                            /--------------------\
		|		+-->| ressources |--------------------------->|Ressources du projet|
		|		|	  +------------+                            \--------------------/
		|		|   +---------------------+                   /--------------------\
		|		+-->| ressources-filtered |------------------>|Ressources filtrées |
		|		|	  +---------------------+                   \--------------------/
		|		|   +---------+                               /--------------------------------\
		|		+-->| filters |------------------------------>|Les filtres pour les ressources |
		|		|	  +---------+		                            \--------------------------------/
		|		|   +-------+                                 /---------------\
		|		+-->| webapp|-------------------------------->|Les sources web|
		|			  +-------+                                 \---------------/
		|   +------+
		+-->| test |
		|	  +------+
		|		|   +------+                                  /------------------------\
		|		+-->| java |--------------------------------->|Sources de tests Java   |
		|		|	  +------+                                  \------------------------/
		|		|   +------------+ 							              /------------------\
		|		+-->| ressources |--------------------------->|Ressources de test|
		|		|	  +------------+	                          \------------------/
		|		|   +---------------------+                   /-----------------------------\
		|		+-->| ressources-filtered |------------------>|Ressources des tests filtrées|
		|		|	  +---------------------+                   \-----------------------------/
		|		|   +---------+                               /----------------------------------------\
		|		+-->| filters |------------------------------>|Les filtres pour les ressources des test|
		|			  +---------+		                            \----------------------------------------/
		|   +----+                                        /-----------------------\
		+-->| it |--------------------------------------->|Les tests d'intégration|
		|	+----+                                          \-----------------------/
		|   +----------+                                  /----------------------\
		+-->| assembly |--------------------------------->|Fichiers d'assemblage |
		|	+----------+                                    \----------------------/
		|   +------+                                      /----------------------------------\
		+-->| site |------------------------------------->|Fichiers pour le site documentaire|
		|	+------+                                        \----------------------------------/
		|   +-------------+                               /----------------------------\
		+-->| LICENSE.txt |------------------------------>|Fichier de license du projet|
		|	+-------------+                                 \----------------------------/
		|   +------------+                                /----------------------------------------------------------\
		+-->| NOTICE.txt |------------------------------->|Notice et attributions exigés par les librairies du projet|
		|	+------------+                                  \----------------------------------------------------------/
		|   +------------+                                /----------------------\
		+-->| README.txt |------------------------------ >|Le lisez-moi du projet|
			+------------+                                  \----------------------/
----

D'après mon exprérience, il est possible mais fortement déconseillé de sortir de ces conventions sous peine de rencontrer des problèmes lors d'utilisation de plugins maven spécifique.

== Les repositories

Vous avez peut-être déjà entendu que Maven télécharge la Terre entière (enfin moins que Docker...) ce qui est en partie vrai.
Pour fonctionner, Maven a besoin de plugins qu'il va par défaut aller chercher sur le https://repo1.maven.org/maven2/[Maven Central].
En effet, même si un projet part du pom minimal vu précédemment, une version de Maven vient avec des plugins à utiliser dans le cycle de vie du projet.
Pour connaître, les versions et les plugins utilisés par défaut, il faut se positionner à la racine du projet et utiliser la commande Maven suivante :

-----

mvn help:effective-pom

-----

Cette commande affiche un pom complet du projet dans la console. Mais pour pouvoir mieux exploiter les informations, il vaut mieux générer un fichier à l'aide de l'option -Doutput=effectivePom.xml.
Ce qui donne :

-----

mvn help:effective-pom -Doutput=effectivePom.xml

-----

Dans ce fichier, se trouve par exemple les informations sur les repositories que Maven utilise pour télécharger les librairies et les plugins.
Dans les faits Maven télécharge la librairie une fois et le stocke dans le repository dit local.

=== Locaux

Le repository local se trouve en standard dans le répertoire %USER_FOLDER%/.m2 (%USER_FOLDER% répretoir utilisateur système). Plus un développeur utilise de plugins, de dépendances et de version différentes plus se répertoire grossit.
Les librairies se trouvent dans le sous répertoire repository de %USER_FOLDER%/.m2.
Le chemin pour une dépendances est déterminée par son groupId/artifactId/version.

Exemple pour la déclration de la librairie ci-dessous.

[source,xml]
-----

<dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
    <version>2.5</version>
</dependency>

-----

Le chemin est : %USER_FOLDER%/.m2/repository/commons-io/commons-io/2.5

=== Distants

Pour trouver une librairie ou un plugin Maven cherche d'abord dans son repository local puis par défaut, il va chercher dans le Maven central.
Le Maven central n'est pas le seul repository distant qui existe.
Après le Maven central, voici une liste des repositories maven les plus connus :

- https://maven.java.net/content/groups/public/
- https://maven.repository.redhat.com/ga/
- http://repo.springsource.org/release/
- ...

Je recommande de n'utiliser d'autres repositories que le central, qu'en cas d'absolue nécéssité.

Pour utiliser d'autres repository, il existe 2 méthodes :

- configurer les informations du repository voulu dans la configuration Maven
- créer un repository intermédiaire entre tous les repositories désirés (cas d'une entreprise par exemple)

Dans ce chapitre, nous allons uniquement aborder l'ajout de repository par configuration. La création d'un repository distant sera vue plus tard dans ce cours.

Un repository se caractérise par les 3 informations essentielles suivantes :

- un identifant unique
- un nom
- une url d'accès

Pour configurer un repository, il faut ajouter la configuration suivante à notre pom.xml :

[source,xml]
-----

<repositories>
    <repository>
      <releases>
        <enabled>false</enabled>
        <updatePolicy>always</updatePolicy>
        <checksumPolicy>warn</checksumPolicy>
      </releases>
      <snapshots>
        <enabled>true</enabled>
        <updatePolicy>never</updatePolicy>
        <checksumPolicy>fail</checksumPolicy>
      </snapshots>
      <id>codehausSnapshots</id>
      <name>Codehaus Snapshots</name>
      <url>http://monrepo.maven.prefere/</url>
      <layout>default</layout>
    </repository>
  </repositories>

-----

Dans la configuration ci-dessus, il s'agit d'un repository de snapshot (version pre-release).
Ce genre de repository est ajouté lorsqu'on a besoin des fonctionnalités d'une librairie dont la version n'est pas encore en release.

Pour plus d'infomation, c'est https://maven.apache.org/pom.html#Repositories[ici].
Pour les repository de plugins Maven, il faut utiliser les balises <pluginRepositories> à la place de repository.

[source,xml]
-----

<pluginRepositories>
    <pluginRepository>
      <id>central</id>
      <name>Central Repository</name>
      <url>http://repo.maven.apache.org/maven2</url>
      <layout>default</layout>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <releases>
        <updatePolicy>never</updatePolicy>
      </releases>
    </pluginRepository>
  </pluginRepositories>

-----

Dans les faits, il faut très rarement ajouter de nouveau repository à notre configuration maven.

== Les Plug-ins Maven

Sans les plugins, Maven ne serait qu'une coquille vide. C'est pourquoi, il télécharge la Terre lors des premières utilisations.

=== Définition

Un plugin Maven est une fonctionnalité. Plus un projet a besoin de fonctionnalité, plus il utilise de plugins.


http://maven.apache.org/plugins/

pour utiliser un plugin .... TODO

=== Les cores

[cols="2*"]
|===
|clean
|suppression du répertoire target

|compiler
|compilation des sources

|deploy
|déploiement du projet sur un repository distant

|failsafe
|exécution des Junit d'intégration dans un classloader spécifique

|install
|installation de l'artefact dans le repository local (.m2)

|resources
|copie des ressources dans le répertoire de sortie pour ajout à l'artefact

|site
|génération du site documentaire

|surefire
|exécution des tests unitaires dans un classloader spécifique

|verifier
|lors des tests d'intégration vérifie l'existence de conditions
|===

=== Les plugins pour packager

[cols="2*"]
|===
|ear
|génération de l'EAR du projet

|ejb
|génération de l'EJB et du client optionnel du projet

|jar
|génération de le JAR du projet

|rar
|génération du RAR du projet

|war
|génération du WAR du projet

|app-client/acr
|génération d'une application client JavaEE à partir du projet

|shade
|génération JAR à partir du projet, comprenant les dépendances.

|source
|génération d'une JAR avec les sources du projet

|===

=== Les plugins de documentation

[cols="2*"]
|===
|changelog
|génération d'une liste des changements à partir du gestionnaire de sources

|changes
|génération d'un rapport à partir du gestionnaire de bug

|checkstyle
|génération d'un rapport checkstyle à partir du code

|doap
|génération d'un fichier DOAP à partir du fichier POM

|docck
|Plugin de vérification de la documentation

|javadoc
|génération de la javadoc à partir du code

|jdeps
|passage de l'outil JDeps sur le projet

|jxr
|génération de pages web des sources à partir du code

|linkcheck
|génération d'un rapport Linkcheck à partir de la documentation

|pmd
|génération d'un rapport PMD à partir du code

|project-info-reports
|génération des différents rapports du projet.

|surefire-report
|génération du rapport de tests unitaires

|===


=== Les plugins d'outillage
[cols="2*"]
|===
|ant
|génération d'un fichier de build ant

|antrun
|exécution d'un ensemble de tâches

|archetype
|génération d'un squelette de projet à partir d'un archetype

|assembly
|génération de package sources, binaires, documentation, ...

|dependency
|gestion des dépendances (copie, décompression) et analyse

|enforcer
|Environmental constraint checking (Maven Version, JDK etc), User Custom Rule Execution.

|gpg
|création de signatures pour les artefacts et les poms.

|help
|Get information about the working environment for the project.

|invoker
|Run a set of Maven projects and verify the output.

|jarsigner
|Signs or verifies project artifacts.

|patch
|Use the gnu patch tool to apply patch files to source code.

|pdf
|Generate a PDF version of your project's documentation.

|plugin
|Create a Maven plugin descriptor for any mojos found in the source tree, to include in the JAR.

|release
|Release the current project - updating the POM and tagging in the SCM.

|remote-resources
|Copy remote resources to the output directory for inclusion in the artifact.

|repository
|Plugin to help with repository-based tasks.

|scm
|Execute SCM commands for the current project.

|scm-publish
|Publish your Maven website to a scm location.

|stage
|Assists with release staging and promotion.

|toolchains
|Allows to share configuration across plugins.

|===

=== Les autres

Il existe une multitude d'autres plugins pour pléthore de besoins :
- des plugins entreprise
- github
- ....

En plus des plugins existants, il est possible de créer son propre plugin. Nous aborderons ce point plus tard.

== Les goals

=== Définition

=== Les goals standards

=== Les goals spécifiques
