= Introduction

	Maven a été créé en 2004 avec la version 1 qui était très proche de Ant. Puis s'est démocratisé, avec la version 2 (2005) puis 3 (2010).
	C'est un outil pour gérer et automatiser la construction des projets Java. Mais pas seulement, il est possible d'utilisé Maven pour des projets PHP ou C++.
	 Cependant l'intégration est beaucoup moins poussée qu'en Java.
	C'est la philosophie de Maven qui l'a rendu populaire : Convention plutôt que configuration.
	En effet, un projet Maven a une structure identique à tous les autres projets Maven et la construction d'un projet suit toujours le même cycle de vie.

.Les différentes étapes se déroulent toujours dans le même ordre :

 * Compilation
 * Execution des tests
 * Déploiements
 * ...

== Environnement

	Maven est disponible sur la plupart des systèmes d'exploitation mais pour l'utiliser, il est nécessaire d'installer le JDK (Java Development Kit) de Java.

== Installation

	1. Téléchargement et installation du JDK sur le site de http://www.oracle.com/technetwork/java/javase/downloads/[Java]
	2. Installé l'éxecutable téléchargé

	definir maven home et ajouter au path
